NAME_LIBRARY=clic3

DIRECTORY_INCLUDE=include
DIRECTORY_LIBRARY=library
DIRECTORY_OBJECTS=objects
DIRECTORY_SOURCES=sources

FILE_LIBRARY=${DIRECTORY_LIBRARY}/${NAME_LIBRARY}.o

FILES_SOURCES=${wildcard ${DIRECTORY_SOURCES}/*.c}
FILES_OBJECTS=${patsubst ${DIRECTORY_SOURCES}/%.c,${DIRECTORY_OBJECTS}/%.o,${FILES_SOURCES}}

CC=gcc
C_FLAGS=-O3 -I${DIRECTORY_INCLUDE}

LD=ld
LD_FLAGS=

${FILE_LIBRARY}: ${FILES_OBJECTS}
	${LD} ${LD_FLAGS} -r $^ -o $@

${DIRECTORY_OBJECTS}/%.o: ${DIRECTORY_SOURCES}/%.c
	${CC} ${C_FLAGS} -c $< -o $@

clean:
	-rm ${DIRECTORY_OBJECTS}/*
	-rm ${FILE_LIBRARY}
