NAME_LIBRARY=clic3

DIRECTORY_INCLUDE=include
DIRECTORY_LIBRARY=library
DIRECTORY_OBJECTS=objects
DIRECTORY_SOURCES=sources
DIRECTORY_UNIT_TESTS=unit_tests
DIRECTORY_BINARY_UNIT_TESTS=${DIRECTORY_UNIT_TESTS}/binary

FILE_BINARY_UNIT_TESTS=${DIRECTORY_BINARY_UNIT_TESTS}/unit_tests
FILE_LIBRARY=${DIRECTORY_LIBRARY}/${NAME_LIBRARY}.o

FILES_SOURCES=${wildcard ${DIRECTORY_SOURCES}/*.c}
FILES_OBJECTS=${patsubst ${DIRECTORY_SOURCES}/%.c,${DIRECTORY_OBJECTS}/%.o,${FILES_SOURCES}}

CC=gcc
C_FLAGS=-O3 -I${DIRECTORY_INCLUDE}

LD=ld
LD_FLAGS=

all: ${FILE_LIBRARY} ${DIRECTORY_UNIT_TESTS} run_unit_tests

${FILE_LIBRARY}: ${DIRECTORY_LIBRARY} ${FILES_OBJECTS}
	${LD} ${LD_FLAGS} -r ${FILES_OBJECTS} -o $@

${DIRECTORY_OBJECTS}/%.o: ${DIRECTORY_SOURCES}/%.c ${DIRECTORY_OBJECTS}
	${CC} ${C_FLAGS} -c $< -o $@

${DIRECTORY_UNIT_TESTS}: ${FILE_LIBRARY} .FORCE
	cd ${DIRECTORY_UNIT_TESTS} && make

run_unit_tests: ${DIRECTORY_UNIT_TESTS}
	./${FILE_BINARY_UNIT_TESTS}

directories: ${DIRECTORY_LIBRARY} ${DIRECTORY_OBJECTS}

${DIRECTORY_LIBRARY}:
	mkdir -p ${DIRECTORY_LIBRARY}

${DIRECTORY_OBJECTS}:
	mkdir -p ${DIRECTORY_OBJECTS}

clean:
	-rm ${DIRECTORY_OBJECTS}/* 2> /dev/null
	-rm ${FILE_LIBRARY} 2> /dev/null

clean_unit_tests:
	cd ${DIRECTORY_UNIT_TESTS} && make clean

clean_all: clean clean_unit_tests

.FORCE:

