name: continuous_integration_build_ios_metal
on:
  push:
    branches: ["core"]
  pull_request:
    branches: ["*"]
env:
  target_device_version: 18.5
  target_metal_standard: metal3.2
jobs:
  continuous_integration_build_ios_metal:
    runs-on: macos-15
    steps:
      - name: git_initialization
        run: git config --global init.defaultBranch core
      - uses: actions/checkout@v5
      - name: make:clic3_ios_metal
        run: make clic3_ios_metal target_device_version=${{ env.target_device_version }} target_device=iphone disable_metal_fast_options=1 target_metal_standard=${{ env.target_metal_standard }}
