name: continuous_integration_build
on:
  push:
    branches: ["core"]
  pull_request:
    branches: ["*"]
env:
  target_device_version_ios: 18.5
  target_device_version_macos: 15.5
jobs:
  continuous_integration_build:
    runs-on: macos-latest
    steps:
      - name: git_initialization
        run: git config --global init.defaultBranch core
      - uses: actions/checkout@v4
      - name: make:clic3_objects
        run: make clic3_objects target_device_version=${{ env.target_device_version_macos }}
      - name: make:clic3_dylib
        run: make clic3_dylib target_device_version=${{ env.target_device_version_macos }}
      - name: make:clic3_dynamic
        run: make clic3_dynamic target_device_version=${{ env.target_device_version_macos }}
      - name: make:clic3_object
        run: make clic3_object target_device_version=${{ env.target_device_version_macos }}
      - name: make:clic3_static
        run: make clic3_static target_device_version=${{ env.target_device_version_macos }}
      - name: make:clic3_ios_objects
        run: make clic3_ios_objects target_device_version=${{ env.target_device_version_ios }} target_device=iphone
      - name: make:clic3_ios_dylib
        run: make clic3_ios_dylib target_device_version=${{ env.target_device_version_ios }} target_device=iphone
      - name: make:clic3_ios_dynamic
        run: make clic3_ios_dynamic target_device_version=${{ env.target_device_version_ios }} target_device=iphone
      - name: make:clic3_ios_object
        run: make clic3_ios_object target_device_version=${{ env.target_device_version_ios }} target_device=iphone
      - name: make:clic3_ios_static
        run: make clic3_ios_static target_device_version=${{ env.target_device_version_ios }} target_device=iphone
      - name: make:unit_tests
        run: make unit_tests
      - name: run:unit_tests
        run: make unit_tests_run
